const fcSmart=(()=>{const a=document.querySelector('#artboard'),make=(axis)=>{let n=document.createElement('i'),l=document.createElement('b');n.append(l);Object.assign(n.style,{display:'none',position:'absolute',zIndex:31,pointerEvents:'none',background:'#d44dff',boxShadow:'0 0 0 1px #fff8,0 0 12px #d44dff',transition:'opacity .12s ease'});Object.assign(l.style,{position:'absolute',background:'#4a135b',color:'#fff',border:'1px solid #f0b5ff',borderRadius:'4px',padding:'2px 5px',fontStyle:'normal',fontSize:'10px',lineHeight:'1',whiteSpace:'nowrap'});if(axis==='x'){Object.assign(n.style,{top:0,bottom:0,width:'2px'});Object.assign(l.style,{top:'5px',left:'5px'})}else{Object.assign(n.style,{left:0,right:0,height:'2px'});Object.assign(l.style,{top:'5px',left:'5px'})}a.append(n);return n},v=make('x'),h=make('y'),set=(n,p,label)=>{if(p==null){n.style.display='none';return}n.style.display='block';if(n===v)n.style.left=p+'%';else n.style.top=p+'%';n.firstChild.textContent=label};return{show:(x,y,id)=>{set(v,x,x===50?'Centro vertical':'Alineado');set(h,y,y===50?'Centro horizontal':'Alineado');let e=a.querySelector('[data-id="'+id+'"]');if(e)e.style.filter=x!=null||y!=null?'drop-shadow(0 0 4px #c64cff)':''},clear:()=>{v.style.display='none';h.style.display='none';a.querySelectorAll('.element').forEach(e=>e.style.filter='')}}})();
const fcSpacing=(()=>{const a=document.querySelector('#artboard'),make=()=>{let n=document.createElement('i'),l=document.createElement('b');n.append(l);Object.assign(n.style,{display:'none',position:'absolute',zIndex:29,pointerEvents:'none',background:'#20c7bf',boxShadow:'0 0 5px #20c7bf'});Object.assign(l.style,{position:'absolute',background:'#063d3b',color:'#e9ffff',border:'1px solid #51eee5',borderRadius:'4px',padding:'2px 4px',fontStyle:'normal',fontSize:'10px',lineHeight:'1',whiteSpace:'nowrap',transform:'translate(-50%,-50%)'});a.append(n);return n},n=[make(),make(),make(),make()];return{show:g=>{n.forEach((x,i)=>{let d=g[i];if(!d){x.style.display='none';return}x.style.display='block';x.firstChild.textContent=d.label;if(d.axis==='x')Object.assign(x.style,{left:d.start+'%',top:d.cross+'%',width:(d.end-d.start)+'%',height:'1px'});else Object.assign(x.style,{left:d.cross+'%',top:d.start+'%',width:'1px',height:(d.end-d.start)+'%'});Object.assign(x.firstChild.style,{left:d.axis==='x'?'50%':'0',top:d.axis==='x'?'0':'50%'})})},clear:()=>n.forEach(x=>x.style.display='none')}})();
(()=>{const $=s=>document.querySelector(s),art=$('#artboard'),panel=$('#panel'),upload=$('#upload'),sheet=$('#sheet'),modal=$('#modal');const uid=()=>Math.random().toString(36).slice(2,9),clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({name:'Tira clásica · 3 fotos',size:'2x6',grid:true,guides:true,snap:true,elements:[{id:uid(),kind:'text',name:'Título',text:'NOCHE DE FOTOS',x:10,y:6,w:80,h:8,font:20,color:'#171720',radius:0,opacity:100,rotate:0,z:5},{id:uid(),kind:'photo',name:'Foto 1',x:10,y:18,w:80,h:20,radius:4,opacity:100,rotate:0,z:2},{id:uid(),kind:'photo',name:'Foto 2',x:10,y:41,w:80,h:20,radius:4,opacity:100,rotate:0,z:3},{id:uid(),kind:'photo',name:'Foto 3',x:10,y:64,w:80,h:20,radius:4,opacity:100,rotate:0,z:4},{id:uid(),kind:'text',name:'Pie',text:'Tu evento · 2026',x:10,y:89,w:80,h:5,font:12,color:'#171720',radius:0,opacity:100,rotate:0,z:6}]});
let s;try{s=JSON.parse(localStorage.getItem('fotocabina-layout-v1'))}catch(e){}if(!s||!s.elements)s=initial();let selected=[],tab='props',history=[],future=[],drag=null,zoom=1,uploadTarget=null;
let marquee=null;
const textFitKeys=new Map(s.elements.filter(e=>e.kind==='text').map(e=>[e.id,[e.text,e.font,e.fontFamily,e.w].join('|')]));
const textTools=document.createElement('span');Object.assign(textTools.style,{display:'none',alignItems:'center',gap:'3px',marginLeft:'5px',paddingLeft:'7px',borderLeft:'1px solid #3a3e4d'});textTools.innerHTML='<select data-tprop="fontFamily" title="Fuente" style="max-width:105px;background:#292c38;color:#fff;border:1px solid #414654;border-radius:5px;padding:5px"><option value="Arial">Sans</option><option value="Trebuchet MS">Humanista</option><option value="Georgia">Serif</option><option value="Courier New">Mono</option></select><button data-tprop="align" data-tvalue="left" title="Alinear a la izquierda">≡</button><button data-tprop="align" data-tvalue="center" title="Centrar texto">☰</button><button data-tprop="align" data-tvalue="right" title="Alinear a la derecha">≡</button><button data-tprop="vAlign" data-tvalue="top" title="Arriba">⇞</button><button data-tprop="vAlign" data-tvalue="center" title="Centrar vertical">↕</button><button data-tprop="vAlign" data-tvalue="bottom" title="Abajo">⇟</button>';document.querySelector('.workbar').append(textTools);function syncTextTools(){let e=selectedEls()[0],show=e&&e.kind==='text';textTools.style.display=show?'inline-flex':'none';if(show){textTools.querySelector('select').value=e.fontFamily||'Arial';textTools.querySelectorAll('button').forEach(b=>b.style.color=b.dataset.tvalue===e[b.dataset.tprop||'']?'#c6ff47':'')}}textTools.addEventListener('change',ev=>{let e=selectedEls()[0];if(e&&e.kind==='text')commit(()=>e.fontFamily=ev.target.value);syncTextTools()});textTools.addEventListener('click',ev=>{let b=ev.target.closest('[data-tprop]'),e=selectedEls()[0];if(!b||!e||e.kind!=='text'||!b.dataset.tvalue)return;commit(()=>e[b.dataset.tprop]=b.dataset.tvalue);syncTextTools()});window.addEventListener('pointerup',()=>setTimeout(syncTextTools,0));
const save=()=>{try{localStorage.setItem('fotocabina-layout-v1',JSON.stringify(s))}catch(e){}};const byId=id=>s.elements.find(e=>e.id===id);const selectedEls=()=>selected.map(byId).filter(Boolean);const snap=n=>s.snap?Math.round(n):n;const num=n=>Math.round(n*10)/10;
function commit(fn){history.push(JSON.stringify(s));if(history.length>60)history.shift();future=[];fn();save();render()}function undo(){if(!history.length)return;future.push(JSON.stringify(s));s=JSON.parse(history.pop());selected=[];save();render()}function redo(){if(!future.length)return;history.push(JSON.stringify(s));s=JSON.parse(future.pop());selected=[];save();render()}
function makeNode(e,interactive){let n=document.createElement('div');n.className='element '+e.kind+(e.locked?' locked':'')+(e.image?' has-image':'');n.dataset.id=e.id;Object.assign(n.style,{left:e.x+'%',top:e.y+'%',width:e.w+'%',height:e.h+'%',zIndex:e.z,opacity:e.opacity/100,transform:'rotate('+e.rotate+'deg)',borderRadius:(e.radius||0)+'%'});if(selected.includes(e.id))n.classList.add('selected');if(e.kind==='text'){n.textContent=e.text;n.style.fontSize=(e.font||16)+'px';n.style.color=e.color||'#171720'}else if(e.kind==='shape'){n.style.background=e.color||'#c6ff47'}else if(e.image){let im=new Image();im.src=e.image;im.alt=e.name;n.append(im)}if(interactive){let tag=document.createElement('span');tag.className='tag';tag.textContent=e.kind==='photo'?'FOTO':e.kind.toUpperCase();n.append(tag);n.addEventListener('pointerdown',ev=>pointerStart(ev,e,false));if(selected.length===1&&selected[0]===e.id&&!e.locked){let h=document.createElement('i');h.className='handle';h.addEventListener('pointerdown',ev=>pointerStart(ev,e,true));n.append(h)}}return n}
function renderArt(){art.style.setProperty('--ratio',s.size==='2x6'?'2/6':'4/6');art.classList.toggle('grid',s.grid);art.classList.toggle('guides',s.guides);art.querySelectorAll('.element').forEach(n=>n.remove());s.elements.slice().sort((a,b)=>a.z-b.z).forEach(e=>art.append(makeNode(e,true)));$('#paper').value=s.size;$('#rename').textContent=s.name;$('#measure').textContent=s.size==='2x6'?'50.8 × 152.4 mm':'101.6 × 152.4 mm';$('#grid').checked=s.grid;$('#guides').checked=s.guides;$('#snap').checked=s.snap;$('#zoom').textContent=Math.round(zoom*100)+'%';art.style.transform='scale('+zoom+')';art.style.transformOrigin='top center'}
function renderPanel(){document.querySelectorAll('.tab').forEach(n=>n.classList.toggle('active',n.dataset.tab===tab));if(tab==='layers'){panel.innerHTML=s.elements.slice().sort((a,b)=>b.z-a.z).map(e=>'<button class="layer '+(selected.includes(e.id)?'active':'')+'" data-select="'+e.id+'"><span class="layer-icon">'+(e.kind==='text'?'T':e.kind==='photo'?'▧':e.kind==='shape'?'◆':'⌁')+'</span><span class="layer-name">'+esc(e.name)+'</span><small>'+ (e.locked?'🔒':'') +'</small></button>').join('');return}let e=selectedEls()[0];if(!e){panel.innerHTML='<div class="empty">Selecciona un elemento del lienzo para editarlo.<br><br>Consejo: mantén <b>Shift</b> para seleccionar varios y alinearlos o distribuirlos.</div>';return}let h='<div class="section-title">'+esc(e.name)+' · '+e.kind+'</div><div class="fields2">'+field('X (%)','x',e.x,'number')+field('Y (%)','y',e.y,'number')+field('Ancho (%)','w',e.w,'number')+field('Alto (%)','h',e.h,'number')+field('Rotación','rotate',e.rotate,'number')+field('Opacidad','opacity',e.opacity,'number')+'</div>';if(e.kind==='text')h+=field('Contenido','text',e.text,'textarea')+field('Tamaño (px)','font',e.font,'number')+field('Color','color',e.color,'color');if(e.kind==='photo'||e.kind==='image')h+='<button class="tool" data-action="upload">Cargar imagen local</button><div class="empty">La imagen queda dentro de este slot. Próximo: recorte y corrección de color por foto.</div>';if(e.kind==='shape')h+=field('Color','color',e.color||'#c6ff47','color');h+=field('Radio de esquina','radius',e.radius||0,'number')+'<label class="toggle"><input type="checkbox" data-prop="locked" '+(e.locked?'checked':'')+'> Bloquear elemento</label><div class="action-grid"><button data-action="duplicate">Duplicar</button><button data-action="front">Traer al frente</button><button data-action="back">Enviar atrás</button><button class="warn" data-action="delete">Eliminar</button></div>';panel.innerHTML=h}
function field(label,prop,value,type){let v=esc(value);return '<div class="field"><label>'+label+'</label>'+(type==='textarea'?'<textarea data-prop="'+prop+'">'+v+'</textarea>':'<input data-prop="'+prop+'" type="'+type+'" value="'+v+'">')+'</div>'}
function render(){renderArt();renderPanel()}function magnet(value,size,axis,pixels){let own=new Set(selected),targets=[0,50,100],best=null,limit=8/pixels*100;s.elements.forEach(o=>{if(!own.has(o.id))targets.push(axis==='x'?o.x:o.y,axis==='x'?o.x+o.w/2:o.y+o.h/2,axis==='x'?o.x+o.w:o.y+o.h)});[value,value+size/2,value+size].forEach(point=>targets.forEach(target=>{let d=Math.abs(point-target);if(d<=limit&&(!best||d<best.d))best={d,target,point}}));return best?{value:num(value+best.target-best.point),target:best.target}:{value:num(snap(value)),target:null}}function pointerStart(ev,e,resize){ev.preventDefault();ev.stopPropagation();if(e.locked)return;if(!resize){if(ev.shiftKey)selected=selected.includes(e.id)?selected.filter(x=>x!==e.id):selected.concat(e.id);else if(!selected.includes(e.id))selected=[e.id]}else selected=[e.id];fcSmart.clear();history.push(JSON.stringify(s));future=[];let r=art.getBoundingClientRect();drag={resize,id:e.id,sx:ev.clientX,sy:ev.clientY,rect:r,starts:selectedEls().map(x=>({id:x.id,x:x.x,y:x.y,w:x.w,h:x.h}))};render()}
window.addEventListener('pointermove',ev=>{if(!drag)return;let dx=(ev.clientX-drag.sx)/drag.rect.width*100,dy=(ev.clientY-drag.sy)/drag.rect.height*100;if(drag.resize){let e=byId(drag.id),a=drag.starts[0];e.w=num(Math.max(5,Math.min(100-a.x,snap(a.w+dx))));e.h=num(Math.max(5,Math.min(100-a.y,snap(a.h+dy))));fcSmart.clear()}else{let a=drag.starts.find(x=>x.id===drag.id),mx=magnet(a.x+dx,a.w,'x',drag.rect.width),my=magnet(a.y+dy,a.h,'y',drag.rect.height),moveX=mx.value-a.x,moveY=my.value-a.y;drag.starts.forEach(start=>{let e=byId(start.id);e.x=num(Math.max(0,Math.min(100-e.w,start.x+moveX)));e.y=num(Math.max(0,Math.min(100-e.h,start.y+moveY)))});renderArt();fcSmart.show(mx.target,my.target,drag.id);return}renderArt()});window.addEventListener('pointerup',()=>{if(drag){drag=null;fcSmart.clear();save();render()}});
function add(kind){commit(()=>{let count=s.elements.filter(e=>e.kind==='photo').length,e={id:uid(),kind,name:kind==='photo'?'Foto '+(count+1):kind==='text'?'Texto nuevo':kind==='shape'?'Forma':'Imagen',x:15,y:Math.min(82,16+count*8),w:70,h:kind==='text'?8:kind==='shape'?18:20,radius:kind==='photo'?4:0,opacity:100,rotate:0,z:Math.max(...s.elements.map(x=>x.z),0)+1};if(kind==='text'){e.text='Escribe aquí';e.font=18;e.color='#171720'}if(kind==='shape')e.color='#c6ff47';s.elements.push(e);selected=[e.id];if(kind==='image'){uploadTarget=e.id;upload.click()}})}
function arrange(action){if(!selected.length)return;commit(()=>{let es=selectedEls(),max=Math.max(...s.elements.map(e=>e.z)),min=Math.min(...s.elements.map(e=>e.z));if(action==='delete'){s.elements=s.elements.filter(e=>!selected.includes(e.id));selected=[]}if(action==='duplicate'){let copies=es.map(e=>Object.assign(clone(e),{id:uid(),name:e.name+' copia',x:Math.min(100-e.w,e.x+2),y:Math.min(100-e.h,e.y+2),z:++max}));s.elements.push(...copies);selected=copies.map(e=>e.id)}if(action==='front')es.forEach(e=>e.z=++max);if(action==='back')es.forEach(e=>e.z=--min);if(action==='upload'){uploadTarget=es[0].id;upload.click()}})}
function align(mode){let es=selectedEls();if(!es.length)return;commit(()=>{let left=Math.min(...es.map(e=>e.x)),right=Math.max(...es.map(e=>e.x+e.w)),top=Math.min(...es.map(e=>e.y)),bottom=Math.max(...es.map(e=>e.y+e.h));if(mode==='left')es.forEach(e=>e.x=left);if(mode==='right')es.forEach(e=>e.x=right-e.w);if(mode==='center')es.forEach(e=>e.x=num((left+right-e.w)/2));if(mode==='top')es.forEach(e=>e.y=top);if(mode==='bottom')es.forEach(e=>e.y=bottom-e.h);if(mode==='middle')es.forEach(e=>e.y=num((top+bottom-e.h)/2));if(mode==='distribute'&&es.length>2){let a=es.slice().sort((x,y)=>x.x+x.w/2-y.x-y.w/2),start=a[0].x+a[0].w/2,end=a[a.length-1].x+a[a.length-1].w/2;a.forEach((e,i)=>e.x=num(start+(end-start)*i/(a.length-1)-e.w/2))}})}
function renderSheet(){sheet.innerHTML='';for(let i=0;i<2;i++){let c=document.createElement('div');c.className='copy';s.elements.slice().sort((a,b)=>a.z-b.z).forEach(e=>c.append(makeNode(e,false)));sheet.append(c)}}
function marqueeStart(ev){if(ev.button!==0)return;ev.preventDefault();fcSmart.clear();let r=art.getBoundingClientRect(),box=document.createElement('i');Object.assign(box.style,{position:'absolute',display:'block',zIndex:30,pointerEvents:'none',background:'rgba(42,136,255,.15)',border:'1px solid #2488ff',boxShadow:'0 0 0 1px #fff9 inset'});art.append(box);marquee={sx:ev.clientX,sy:ev.clientY,rect:r,box,base:ev.shiftKey?selected.slice():[]};if(!ev.shiftKey)selected=[];renderArt();renderPanel()}
function updateMarquee(ev){if(!marquee)return;let m=marquee,x=Math.min(m.sx,ev.clientX),y=Math.min(m.sy,ev.clientY),w=Math.abs(ev.clientX-m.sx),h=Math.abs(ev.clientY-m.sy),left=(x-m.rect.left)/m.rect.width*100,top=(y-m.rect.top)/m.rect.height*100,width=w/m.rect.width*100,height=h/m.rect.height*100;Object.assign(m.box.style,{left:left+'%',top:top+'%',width:width+'%',height:height+'%'});let hit=s.elements.filter(e=>e.x<left+width&&e.x+e.w>left&&e.y<top+height&&e.y+e.h>top).map(e=>e.id);selected=Array.from(new Set(m.base.concat(hit)));renderArt()}
art.addEventListener('pointerdown',marqueeStart);art.addEventListener('click',ev=>ev.stopPropagation());window.addEventListener('pointermove',updateMarquee);window.addEventListener('pointerup',()=>{if(!marquee)return;marquee.box.remove();marquee=null;render()});
function gapLabel(g,axis){let mm=(axis==='x'?(s.size==='2x6'?50.8:101.6):152.4)*g/100;return num(mm)+' mm'}function showSpacing(){if(!drag||drag.resize){fcSpacing.clear();return}let e=byId(drag.id),others=s.elements.filter(o=>!selected.includes(o.id)),guides=[],overY=o=>o.y<e.y+e.h&&o.y+o.h>e.y,overX=o=>o.x<e.x+e.w&&o.x+o.w>e.x,left=others.filter(o=>overY(o)&&o.x+o.w<=e.x).sort((a,b)=>b.x+b.w-a.x-a.w)[0],right=others.filter(o=>overY(o)&&o.x>=e.x+e.w).sort((a,b)=>a.x-b.x)[0],top=others.filter(o=>overX(o)&&o.y+o.h<=e.y).sort((a,b)=>b.y+b.h-a.y-a.h)[0],bottom=others.filter(o=>overX(o)&&o.y>=e.y+e.h).sort((a,b)=>a.y-b.y)[0],crossY=o=>num((Math.max(e.y,o.y)+Math.min(e.y+e.h,o.y+o.h))/2),crossX=o=>num((Math.max(e.x,o.x)+Math.min(e.x+e.w,o.x+o.w))/2);if(left&&e.x-left.x-left.w>.2)guides.push({axis:'x',start:left.x+left.w,end:e.x,cross:crossY(left),label:gapLabel(e.x-left.x-left.w,'x')});if(right&&right.x-e.x-e.w>.2)guides.push({axis:'x',start:e.x+e.w,end:right.x,cross:crossY(right),label:gapLabel(right.x-e.x-e.w,'x')});if(top&&e.y-top.y-top.h>.2)guides.push({axis:'y',start:top.y+top.h,end:e.y,cross:crossX(top),label:gapLabel(e.y-top.y-top.h,'y')});if(bottom&&bottom.y-e.y-e.h>.2)guides.push({axis:'y',start:e.y+e.h,end:bottom.y,cross:crossX(bottom),label:gapLabel(bottom.y-e.y-e.h,'y')});fcSpacing.show(guides)}window.addEventListener('pointermove',showSpacing);window.addEventListener('pointerup',()=>fcSpacing.clear());
function equalSpacing(){
  if(!drag||drag.resize||!s.snap)return;
  let moving=byId(drag.id),others=s.elements.filter(o=>!selected.includes(o.id)),best=null;
  function find(axis){
    let pos=o=>axis==='y'?o.y:o.x;
    let len=o=>axis==='y'?o.h:o.w;
    let movingPos=axis==='y'?moving.y:moving.x;
    let movingLen=axis==='y'?moving.h:moving.w;
    let pixels=axis==='y'?drag.rect.height:drag.rect.width;
    let limit=8/pixels*100;
    let overlaps=o=>axis==='y'?o.x<moving.x+moving.w&&o.x+o.w>moving.x:o.y<moving.y+moving.h&&o.y+o.h>moving.y;
    let list=others.filter(overlaps).sort((a,b)=>pos(a)-pos(b));
    for(let i=0;i<list.length-1;i++){
      let a=list[i],b=list[i+1],gap=pos(b)-pos(a)-len(a);
      if(gap<.2)continue;
      let options=[{target:pos(b)+len(b)+gap,anchor:b,after:true},{target:pos(a)-gap-movingLen,anchor:a,after:false}];
      for(let j=0;j<options.length;j++){
        let option=options[j],d=Math.abs(option.target-movingPos);
        if(option.target>=0&&option.target<=100-movingLen&&d<=limit&&(!best||d<best.d))best={axis,target:option.target,anchor:option.anchor,after:option.after,gap,d};
      }
    }
  }
  find('y');find('x');if(!best)return;
  let delta=best.target-(best.axis==='y'?moving.y:moving.x);
  selectedEls().forEach(o=>{if(best.axis==='y')o.y=num(Math.max(0,Math.min(100-o.h,o.y+delta)));else o.x=num(Math.max(0,Math.min(100-o.w,o.x+delta)))});
  renderArt();
  let start=best.after?(best.axis==='y'?best.anchor.y+best.anchor.h:best.anchor.x+best.anchor.w):best.target+(best.axis==='y'?moving.h:moving.w);
  let end=best.after?best.target:(best.axis==='y'?best.anchor.y:best.anchor.x);
  let cross=best.axis==='y'?num(moving.x+moving.w/2):num(moving.y+moving.h/2);
  fcSpacing.show([{axis:best.axis,start,end,cross,label:gapLabel(best.gap,best.axis)+' · igual'}]);
}
window.addEventListener('pointermove',equalSpacing);
function fitTextBoxes(){let canvasHeight=art.clientHeight;if(!canvasHeight)return;s.elements.filter(e=>e.kind==='text').forEach(e=>{let n=art.querySelector('[data-id="'+e.id+'"]');if(!n)return;let horizontal=e.align||'center',vertical=e.vAlign||'center',key=[e.text,e.font,e.fontFamily,e.w].join('|');Object.assign(n.style,{fontFamily:e.fontFamily||'Arial, sans-serif',justifyContent:horizontal==='left'?'flex-start':horizontal==='right'?'flex-end':'center',alignItems:vertical==='top'?'flex-start':vertical==='bottom'?'flex-end':'center',textAlign:horizontal,whiteSpace:'pre-wrap',overflowWrap:'anywhere',wordBreak:'break-word',padding:'2px 3px',overflow:'hidden'});if(textFitKeys.get(e.id)===key)return;textFitKeys.set(e.id,key);let needed=num(n.scrollHeight/canvasHeight*100);if(needed>e.h+.1){e.h=Math.min(100-e.y,needed);n.style.height=e.h+'%';save()}})}new MutationObserver(fitTextBoxes).observe(art,{childList:true});
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),400)}
document.addEventListener('click',ev=>{let addBtn=ev.target.closest('[data-add]'),a=ev.target.closest('[data-arrange]'),al=ev.target.closest('[data-align]'),t=ev.target.closest('[data-tab]'),sel=ev.target.closest('[data-select]');if(addBtn)add(addBtn.dataset.add);if(a)arrange(a.dataset.arrange);if(al)align(al.dataset.align);if(t){tab=t.dataset.tab;renderPanel()}if(sel){selected=[sel.dataset.select];render()}if(ev.target===art){selected=[];render()}});
panel.addEventListener('change',ev=>{let p=ev.target.dataset.prop,e=selectedEls()[0];if(!p||!e)return;commit(()=>{let v=ev.target.type==='checkbox'?ev.target.checked:ev.target.value;e[p]=['x','y','w','h','rotate','opacity','font','radius'].includes(p)?Number(v):v})});panel.addEventListener('click',ev=>{let b=ev.target.closest('[data-action]');if(b)arrange(b.dataset.action)});
$('#undo').onclick=undo;$('#redo').onclick=redo;$('#paper').onchange=ev=>commit(()=>s.size=ev.target.value);$('#grid').onchange=ev=>{s.grid=ev.target.checked;save();renderArt()};$('#guides').onchange=ev=>{s.guides=ev.target.checked;save();renderArt()};$('#snap').onchange=ev=>{s.snap=ev.target.checked;save()};document.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{zoom=Math.max(.65,Math.min(1.4,zoom+(b.dataset.zoom==='+'?.1:-.1)));renderArt()});$('#rename').onclick=()=>{let n=prompt('Nombre de la plantilla',s.name);if(n)commit(()=>s.name=n)};$('#export').onclick=()=>download((s.name||'plantilla').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json',JSON.stringify(s,null,2),'application/json');
$('#preview').onclick=()=>{renderSheet();modal.classList.add('show')};const close=()=>modal.classList.remove('show');$('#closeModal').onclick=close;$('#closeModal2').onclick=close;$('#print').onclick=()=>{let css='@page{size:4in 6in;margin:0}*{box-sizing:border-box}body{margin:0}.page{width:4in;height:6in;display:grid;grid-template-columns:1fr 1fr;padding:.06in;gap:.02in}.copy{position:relative;overflow:hidden}.e{position:absolute;overflow:hidden;line-height:1.07;font-family:Arial,sans-serif}.e img{width:100%;height:100%;object-fit:cover}.photo{background:#59606d;color:#fff;display:grid;place-items:center}.shape{background:#c6ff47}';let each=s.elements.map(e=>'<div class="e '+e.kind+'" style="left:'+e.x+'%;top:'+e.y+'%;width:'+e.w+'%;height:'+e.h+'%;z-index:'+e.z+';opacity:'+(e.opacity/100)+';transform:rotate('+e.rotate+'deg);border-radius:'+(e.radius||0)+'%;font-size:'+(e.font||0)+'px;color:'+(e.color||'#171720')+'">'+(e.image?'<img src="'+e.image+'">':e.kind==='text'?esc(e.text):e.kind==='photo'?'FOTO':'')+'</div>').join('');let w=window.open('','_blank');w.document.write('<title>FotoCabina 4x6</title><style>'+css+'</style><div class="page"><div class="copy">'+each+'</div><div class="copy">'+each+'</div></div>');w.document.close();w.onload=()=>w.print()};
upload.onchange=()=>{let f=upload.files&&upload.files[0],e=byId(uploadTarget);if(!f||!e)return;let r=new FileReader();r.onload=()=>commit(()=>{e.image=r.result;e.kind=e.kind==='photo'?'photo':'image'});r.readAsDataURL(f);upload.value=''};function nudgeGuide(){let es=selectedEls(),left=Math.min(...es.map(e=>e.x)),right=Math.max(...es.map(e=>e.x+e.w)),top=Math.min(...es.map(e=>e.y)),bottom=Math.max(...es.map(e=>e.y+e.h)),gx=null,gy=null;if(Math.abs((left+right)/2-50)<=.75){let d=50-(left+right)/2;es.forEach(e=>e.x=num(Math.max(0,Math.min(100-e.w,e.x+d))));gx=50}if(Math.abs((top+bottom)/2-50)<=.75){let d=50-(top+bottom)/2;es.forEach(e=>e.y=num(Math.max(0,Math.min(100-e.h,e.y+d))));gy=50}if(gx!=null||gy!=null){save();render();fcSmart.show(gx,gy,es[0].id);clearTimeout(nudgeGuide.timer);nudgeGuide.timer=setTimeout(()=>fcSmart.clear(),700)}}document.addEventListener('keydown',ev=>{let tag=document.activeElement.tagName;if(tag==='INPUT'||tag==='TEXTAREA')return;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?redo():undo()}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='d'){ev.preventDefault();arrange('duplicate')}if(ev.key==='Delete'||ev.key==='Backspace')arrange('delete');if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)&&selected.length){ev.preventDefault();let dx=ev.key==='ArrowLeft'?-1:ev.key==='ArrowRight'?1:0,dy=ev.key==='ArrowUp'?-1:ev.key==='ArrowDown'?1:0;commit(()=>selectedEls().forEach(e=>{e.x=Math.max(0,Math.min(100-e.w,e.x+dx));e.y=Math.max(0,Math.min(100-e.h,e.y+dy))}));nudgeGuide()}});render()})();
